
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 97
#define YY_END_OF_BUFFER 98
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[348] =
    {   0,
        0,    0,   98,   96,    1,    1,   83,   96,   95,   94,
       91,   96,   71,   72,   89,   87,   78,   88,   79,   90,
       39,   39,   86,   77,   82,   80,   81,   85,   75,   76,
       93,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   73,   92,   74,
       84,    1,   58,    0,   51,    0,   95,   59,   70,    0,
        0,   68,   61,   66,   62,   67,    0,   44,    0,    3,
       69,   43,   41,    0,    0,   46,    0,   39,    0,    0,
       39,    0,   63,   57,   55,   56,   65,   95,   95,   95,
       95,   95,   95,   11,   95,   95,   95,   95,   95,   95,

       95,    7,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   60,   51,    0,    0,    0,    0,   50,    0,    0,
        0,   54,   44,   44,    0,    0,    0,    0,    3,   43,
       43,    0,   41,   41,    0,    0,   42,    0,   45,    0,
       40,   41,   39,    0,   39,   64,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,    5,
       95,   24,   95,   33,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   35,   95,   95,
       95,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   44,    0,    2,   43,    0,    0,   43,   42,   42,
        0,   45,   45,    0,    0,    0,   40,   40,    0,    0,
       41,    0,   39,    0,   95,   95,   95,   38,   95,   95,
       95,   18,   21,   95,   95,   95,   95,   95,   29,   53,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   13,
       95,   49,   27,   95,   95,    0,    0,    0,    0,    0,
        0,   44,    0,    0,    2,   43,    0,    0,    0,    0,
        0,   47,   95,   95,   14,   28,   95,   95,   95,   25,
       30,   95,   95,   95,   95,   95,   95,   95,   95,   31,
       95,   17,   32,   37,    0,    0,    0,    0,    0,    0,

        0,   48,   47,   47,    0,    6,   95,   95,   15,   95,
       95,   95,   95,   95,   19,   36,   22,   26,   95,   20,
       52,    0,    0,    0,   48,   48,    0,   10,   95,   23,
       95,    8,   34,   12,   95,    0,    4,   95,   95,    0,
       95,   95,   16,   95,   95,    9,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,    1,   30,   31,   30,   32,   33,   32,
        7,    7,    7,    7,    7,   34,    7,    7,    7,   35,
        7,    7,    7,    7,    7,    7,    7,   36,    7,    7,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,    7,   51,   52,   53,   54,
       55,   56,    7,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    2,    2,    1,    1,    3,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        6,    6,    6,    1,    1,    1,    1,    1,    1,    6,
        6,    6,    6,    7,    8,    3,    1,    1,    1,    1,
        8,    6,    6,    6,    6,    6,    6,    3,    3,    3,
        3,    7,    3,    3,    3,    8,    3,    3,    3,    9,
        3,    3,    3,    3,    3,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[371] =
    {   0,
        0,    0,  788,  874,   68,   71,  760,   70,    0,  874,
       68,  748,  874,  874,  757,   64,  874,   63,   63,   74,
       92,  139,  874,  874,   62,  756,   66,  874,  874,  874,
      874,  724,   41,   48,  726,   53,   77,   87,  725,   58,
       60,  733,   83,   73,   94,  728,  725,  874,  707,  874,
      874,  148,  874,   93,  752,  186,    0,  874,  874,  747,
      241,  874,  874,  874,  874,  874,  739,  283,  736,    0,
      874,  155,  314,  350,  126,  874,  195,  874,  730,  200,
      215,  245,  874,  874,  874,  874,  714,  683,  685,  692,
      695,  694,  680,  673,  674,  671,  670,  676,  661,  659,

      656,    0,  656,  647,  650,  641,  650,  652,  637,  643,
      648,  104,  648,  612,  613,  107,  605,  602,  608,  606,
      609,  874,  874,  163,  233,  253,  591,  874,  298,  322,
      589,  874,    0,  874,  365,  379,  634,  176,    0,  402,
      874,  389,    0,  874,  395,  409,  273,  290,  419,    0,
      322,  433,    0,  448,  456,  874,  599,  592,  601,  585,
      582,  579,  594,  590,  564,  570,  557,  570,  569,    0,
      558,    0,  559,    0,  554,  540,  531,  522,  530,  525,
      513,  513,  515,  510,  490,  490,  498,    0,  496,  475,
      474,  166,  115,  187,  466,  175,    0,  330,  509,    0,

      461,  471,  185,  874,    0,  479,  486,  502,  476,  874,
      163,  510,  874,  517,  241,  175,  518,  874,  546,  529,
        0,  556,    0,  567,  458,  468,  462,    0,  453,  423,
      413,    0,    0,  409,  416,  409,  400,  412,    0,    0,
      415,  406,  404,  395,  387,  380,  383,  370,  377,    0,
      357,    0,    0,  367,  362,  189,  220,  603,  242,    0,
        0,  573,  580,  393,  391,  607,  612,  515,  650,  563,
      655,  660,  335,  351,    0,    0,  338,  344,  344,    0,
        0,  327,  329,  317,  316,  324,  320,  310,  318,    0,
      301,  296,    0,    0,  243,  678,  689,  293,    0,    0,

      666,  698,  703,  874,  732,    0,  291,  278,    0,  269,
      280,  277,  263,  250,    0,    0,    0,    0,  239,    0,
      251,  740,  284,    0,  744,  874,  749,    0,  241,    0,
      231,    0,    0,    0,  229,    0,    0,  219,  227,    0,
      212,  204,    0,  204,  197,    0,  874,  791,  798,  807,
      816,  825,  830,  831,  835,  226,  840,  848,  224,  222,
      857,  861,  206,  193,  864,  191,  173,  148,  104,   75
    } ;

static const flex_int16_t yy_def[371] =
    {   0,
      347,    1,  347,  347,  347,  347,  347,  348,  349,  347,
      347,  350,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  347,  347,  347,
      347,  347,  347,  348,  347,  347,  349,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  351,  352,
      347,  347,  347,  347,  347,  347,  347,  347,  353,  347,
       22,  347,  347,  347,  347,  347,  347,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,

      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  347,  347,  347,  348,  348,  354,  347,  347,  347,
      355,  347,   68,  347,  347,  347,  351,  351,  352,  347,
      347,  347,   73,  347,  347,  347,  347,  347,  347,  356,
      357,   73,   81,  347,   81,  347,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  347,  358,  358,  348,  348,  359,  347,  347,  360,

      347,  347,  361,  347,  140,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  362,  356,  357,  347,  347,  217,
      152,  347,  155,  347,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  358,  358,  347,  358,  363,
      364,  347,  347,  351,  351,  347,  347,  362,  347,  362,
      347,  347,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  358,  358,  358,  365,  366,  367,

      347,  347,  347,  347,  347,  349,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      358,  358,  358,  368,  347,  347,  347,  349,  349,  349,
      349,  349,  349,  349,  349,  369,  349,  349,  349,  370,
      349,  349,  349,  349,  349,  349,    0,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347
    } ;

static const flex_int16_t yy_nxt[944] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   23,   24,   25,   26,   27,   28,    9,
        9,    9,    9,    9,    9,    9,   29,    4,   30,   31,
        9,   32,   33,   34,   35,   36,   37,    9,    9,   38,
        9,   39,    9,   40,    9,   41,   42,   43,   44,    9,
       45,   46,    9,   47,    9,   48,   49,   50,   51,   52,
       52,   52,   52,   52,   52,   55,   58,   63,   65,   67,
      256,   68,   68,   68,   68,   68,   69,   83,   84,   66,
       64,   70,   86,   87,   59,   89,   91,   90,  123,   92,

       71,  108,   93,  106,   95,  109,   96,   56,   72,  340,
       73,   73,   73,   73,   74,   97,  110,  107,   98,  111,
      257,  116,   75,   76,   77,   78,   99,   79,  100,  117,
       56,  101,   80,  102,   75,  118,   76,   77,   76,  103,
      104,  113,  114,   78,  147,  147,  115,  180,  119,   52,
       52,   52,  258,  336,   79,   72,  185,   81,   81,   81,
       81,   81,  181,  186,  192,  193,  194,  192,  193,  194,
       76,   77,   78,  140,  140,  140,  140,  140,   60,   82,
      123,  209,  209,   76,   77,   76,  141,  142,  203,  259,
       78,   54,  257,  204,  257,   54,   54,  203,  300,  141,

      142,  141,  265,  211,  125,  125,  125,  126,  148,  219,
      148,  299,   56,  149,  149,  149,  149,  149,  152,  152,
      152,  152,   74,   54,  258,  295,  258,  261,   54,  260,
      219,  215,   54,  153,  153,  153,  153,  153,  123,   54,
       80,  346,   54,   54,   54,  127,   60,  257,  321,  345,
       60,  195,  195,  195,  195,  154,  321,  258,  123,  129,
      129,  129,  130,  155,  155,  155,  155,  155,  344,  343,
       56,  196,  196,  196,  196,  269,  342,  341,   60,  258,
      258,  270,  339,   60,  338,   82,  337,   60,  258,  257,
       56,  209,  209,  335,   60,  334,  269,   60,   60,   60,

      131,  133,  133,  133,  133,  133,  210,  128,  149,  149,
      149,  149,  149,  211,  134,  135,  198,  198,  198,  198,
      333,  258,  332,  136,  210,  331,  330,  134,  135,  134,
       72,  128,  143,  143,  143,  143,   74,  329,  216,  128,
      199,  199,  199,  199,  328,   76,   77,  144,  199,  199,
      199,  199,  298,  320,  145,  218,  219,  319,   76,   77,
       76,  318,  220,  317,  316,  144,   72,  315,   74,   74,
       74,   74,   74,  218,  314,  313,  312,  219,  201,  311,
      201,   76,   77,  202,  202,  202,  202,  202,  310,  309,
      146,  308,  307,  306,   76,   77,   76,  133,  133,  133,

      133,  133,  207,  138,  207,  138,  294,  208,  208,  208,
      208,  208,  293,  143,  143,  143,  143,   74,  292,  136,
      205,  205,  205,  205,  205,  291,  290,   74,   74,   74,
       74,   74,  289,  141,  142,  145,  288,  212,  212,  212,
      212,  212,  206,  287,  286,  285,  141,  142,  141,  146,
      213,  221,  221,  221,  221,  284,  283,  282,  281,  214,
      280,  252,  279,  213,  278,  213,  153,  153,  153,  153,
      153,  123,  277,  222,  223,  223,  223,  223,  223,  202,
      202,  202,  202,  202,  196,  196,  196,  196,  154,  262,
      262,  262,  262,  262,  209,  209,  224,  205,  205,  205,

      205,  205,  134,   56,  208,  208,  208,  208,  208,  210,
      276,  263,  275,  274,  273,  134,  211,  134,  128,  206,
      266,  266,  266,  266,  266,  255,  254,  210,  212,  212,
      212,  212,  212,  141,  216,  212,  212,  212,  212,  212,
      253,  213,  267,  252,  251,  347,  141,  250,  141,  269,
      214,  218,  219,  249,  213,  270,  213,  214,  220,  271,
      248,  271,  347,  347,  272,  272,  272,  272,  272,  218,
      269,  247,  246,  219,  221,  221,  221,  221,   74,  245,
      347,  244,  243,  242,  347,  223,  223,  223,  223,  223,
      241,  262,  262,  262,  262,  262,  222,  347,  262,  262,

      262,  262,  262,  270,  134,  240,  239,  224,  256,  238,
      237,  236,  256,  263,  235,  234,  233,  134,  347,  134,
      263,  296,  296,  296,  297,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  232,  231,  230,  141,  229,
      256,  228,  227,  226,  225,  256,  138,  267,  131,  256,
      127,  141,  267,  141,  191,  190,  256,  189,  188,  256,
      256,  256,  298,  301,  187,  301,  184,  183,  302,  302,
      302,  302,  302,  272,  272,  272,  272,  272,  303,  303,
      303,  303,  303,  257,  302,  302,  302,  302,  302,  182,
      179,  304,  178,  177,  257,  176,  322,  322,  322,  322,

      305,  175,  174,  173,  304,  172,  304,  323,  323,  323,
      323,  171,  170,  169,  168,  258,  325,  325,  325,  325,
      325,  303,  303,  303,  303,  303,  258,  167,  166,  326,
      165,  164,  163,  162,  304,  161,  160,  159,  327,  158,
      157,  156,  326,  305,  326,  257,  150,  304,  138,  304,
      303,  303,  303,  303,  303,  132,  128,  124,  323,  323,
      323,  323,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  305,  122,  121,  326,  120,  258,  112,  105,
       94,   88,   85,   62,  327,   61,   53,  347,  326,  327,
      326,   54,  347,   54,   54,   54,   54,   54,   54,   54,

       57,  347,  347,   57,   57,   57,   57,   60,  347,   60,
      347,   60,   60,   60,   60,   60,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  139,  347,  139,  139,  139,
      139,  139,  139,  139,  151,  151,  197,  347,  347,  197,
      200,  347,  347,  200,  217,  217,  217,  217,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  268,  347,  268,  324,
      347,  347,  324,    3,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347
    } ;

static const flex_int16_t yy_chk[944] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    6,    6,    6,    8,   11,   16,   18,   19,
      370,   19,   19,   19,   19,   19,   20,   25,   25,   18,
       16,   20,   27,   27,   11,   33,   34,   33,   54,   34,

       20,   41,   34,   40,   36,   41,   36,    8,   21,  369,
       21,   21,   21,   21,   21,   36,   41,   40,   37,   41,
      193,   44,   21,   21,   21,   21,   37,   21,   37,   44,
       54,   37,   21,   38,   21,   45,   21,   21,   21,   38,
       38,   43,   43,   21,   75,   75,   43,  112,   45,   52,
       52,   52,  193,  368,   21,   22,  116,   22,   22,   22,
       22,   22,  112,  116,  124,  124,  124,  192,  192,  192,
       22,   22,   22,   72,   72,   72,   72,   72,  367,   22,
      196,  211,  211,   22,   22,   22,   72,   72,  138,  194,
       22,   56,  194,  138,  256,   56,  366,  203,  364,   72,

       72,   72,  203,  211,   56,   56,   56,   56,   77,  216,
       77,  363,  196,   77,   77,   77,   77,   77,   80,   80,
       80,   80,   80,   56,  194,  257,  256,  360,   56,  359,
      216,  356,   56,   81,   81,   81,   81,   81,  125,   56,
       80,  345,   56,   56,   56,   56,   61,  259,  295,  344,
       61,  125,  125,  125,  125,   81,  321,  257,  126,   61,
       61,   61,   61,   82,   82,   82,   82,   82,  342,  341,
      125,  126,  126,  126,  126,  215,  339,  338,   61,  259,
      295,  215,  335,   61,  331,   82,  329,   61,  321,  323,
      126,  147,  147,  319,   61,  314,  215,   61,   61,   61,

       61,   68,   68,   68,   68,   68,  147,  129,  148,  148,
      148,  148,  148,  147,   68,   68,  129,  129,  129,  129,
      313,  323,  312,   68,  147,  311,  310,   68,   68,   68,
       73,  130,   73,   73,   73,   73,   73,  308,  151,  198,
      130,  130,  130,  130,  307,   73,   73,   73,  198,  198,
      198,  198,  298,  292,   73,  151,  151,  291,   73,   73,
       73,  289,  151,  288,  287,   73,   74,  286,   74,   74,
       74,   74,   74,  151,  285,  284,  283,  151,  135,  282,
      135,   74,   74,  135,  135,  135,  135,  135,  279,  278,
       74,  277,  274,  273,   74,   74,   74,  136,  136,  136,

      136,  136,  142,  265,  142,  264,  255,  142,  142,  142,
      142,  142,  254,  145,  145,  145,  145,  145,  251,  136,
      140,  140,  140,  140,  140,  249,  248,  146,  146,  146,
      146,  146,  247,  140,  140,  145,  246,  149,  149,  149,
      149,  149,  140,  245,  244,  243,  140,  140,  140,  146,
      149,  152,  152,  152,  152,  242,  241,  238,  237,  149,
      236,  235,  234,  149,  231,  149,  154,  154,  154,  154,
      154,  195,  230,  152,  155,  155,  155,  155,  155,  201,
      201,  201,  201,  201,  195,  195,  195,  195,  154,  202,
      202,  202,  202,  202,  209,  209,  155,  206,  206,  206,

      206,  206,  202,  195,  207,  207,  207,  207,  207,  209,
      229,  202,  227,  226,  225,  202,  209,  202,  199,  206,
      208,  208,  208,  208,  208,  191,  190,  209,  212,  212,
      212,  212,  212,  208,  217,  214,  214,  214,  214,  214,
      189,  212,  208,  187,  186,  220,  208,  185,  208,  268,
      212,  217,  217,  184,  212,  268,  212,  214,  217,  219,
      183,  219,  220,  220,  219,  219,  219,  219,  219,  217,
      268,  182,  181,  217,  222,  222,  222,  222,  222,  180,
      220,  179,  178,  177,  220,  224,  224,  224,  224,  224,
      176,  262,  262,  262,  262,  262,  222,  270,  263,  263,

      263,  263,  263,  270,  262,  175,  173,  224,  258,  171,
      169,  168,  258,  262,  167,  166,  165,  262,  270,  262,
      263,  258,  258,  258,  258,  266,  266,  266,  266,  266,
      267,  267,  267,  267,  267,  164,  163,  162,  266,  161,
      258,  160,  159,  158,  157,  258,  137,  266,  131,  258,
      127,  266,  267,  266,  121,  120,  258,  119,  118,  258,
      258,  258,  258,  269,  117,  269,  115,  114,  269,  269,
      269,  269,  269,  271,  271,  271,  271,  271,  272,  272,
      272,  272,  272,  296,  301,  301,  301,  301,  301,  113,
      111,  272,  110,  109,  297,  108,  296,  296,  296,  296,

      272,  107,  106,  105,  272,  104,  272,  297,  297,  297,
      297,  103,  101,  100,   99,  296,  302,  302,  302,  302,
      302,  303,  303,  303,  303,  303,  297,   98,   97,  302,
       96,   95,   94,   93,  303,   92,   91,   90,  302,   89,
       88,   87,  302,  303,  302,  322,   79,  303,   69,  303,
      305,  305,  305,  305,  305,   67,   60,   55,  322,  322,
      322,  322,  325,  325,  325,  325,  325,  327,  327,  327,
      327,  327,  305,   49,   47,  325,   46,  322,   42,   39,
       35,   32,   26,   15,  325,   12,    7,    3,  325,  327,
      325,  348,    0,  348,  348,  348,  348,  348,  348,  348,

      349,    0,    0,  349,  349,  349,  349,  350,    0,  350,
        0,  350,  350,  350,  350,  350,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  352,    0,  352,  352,  352,
      352,  352,  352,  352,  353,  353,  354,    0,    0,  354,
      355,    0,    0,  355,  357,  357,  357,  357,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  362,    0,  362,  365,
        0,    0,  365,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[98] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 13 "lexer.l"
	#include <bits/stdc++.h>
    // #include "parser.tab.h"
    #include "grammer.tab.h"
    #include "table.h"
    #define HANDLE(X) return X;

    // #define CONCATENATE(X) \
    //     const char* s1 = #X "("; \
    //     const char* s2 = ")"; \
    //     size_t new_len = strlen(yytext) + strlen(s1) + strlen(s2); \
    //     char* new_ch = (char*)malloc(new_len + 1); \
    //     strcpy(new_ch, s1); \
    //     strcat(new_ch, yytext); \
    //     strcat(new_ch, s2); \
    //     yylval.ST.sym = strdup(new_ch); \
    //     free(new_ch); \



#line 819 "lex.yy.c"
#line 820 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 37 "lexer.l"


#line 1040 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 348 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 874 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 39 "lexer.l"
{ /* whitespaces */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 41 "lexer.l"
{ ;/* Multiline Comment  *? make it lazy to add as less characters as possible */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "lexer.l"
{ /* Singleline Comment using the definition of InputCharacter */}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 46 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(CONTINUE) /* Reserved Keywords */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 47 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(FOR) /* Reserved Keywords */ }   
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(ASSERT) /* Reserved Keywords */ }         
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(IF) /* Reserved Keywords */ }       
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(PACKAGE) /* Reserved Keywords */ }        
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(SYNCRO) /* Reserved Keywords */ }            
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(BOOLEAN) /* Reserved Keywords */ }        
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 53 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(DO) /* Reserved Keywords */ }           
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(PRIVATE) /* Reserved Keywords */ }           
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(THIS) /* Reserved Keywords */ }             
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(BREAK) /* Reserved Keywords */ }               
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 57 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(DOUBLE) /* Reserved Keywords */ }               
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 58 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(IMPLEMENTS) /* Reserved Keywords */ }                 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(THROW) /* Reserved Keywords */ }            
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(ELSE) /* Reserved Keywords */ }           
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(PUBLIC) /* Reserved Keywords */ }               
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 62 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(THROWS) /* Reserved Keywords */ }                 
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(ENUM) /* Reserved Keywords */ }                 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(RETURN) /* Reserved Keywords */ }                         
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(EXTENDS) /* Reserved Keywords */ }               
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(INT) /* Reserved Keywords */ }             
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(FINAL) /* Reserved Keywords */ }              
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(STATIC) /* Reserved Keywords */ }                      
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(VOID) /* Reserved Keywords */ }                                         
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 70 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(CLASS) /* Reserved Keywords */ }                      
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 71 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(LONG) /* Reserved Keywords */ }                       
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(FLOAT) /* Reserved Keywords */ }                        
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(SUPER) /* Reserved Keywords */ }                      
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(WHILE) /* Reserved Keywords */ }                                               
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(NEW) /* Reserved Keywords */ }  
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(PERMITS) /* Contextual Keyword */ }   
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(VAR) /* Contextual Keyword */ }      
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(RECORD) /* Contextual Keyword */ }         
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(YIELD) /* Contextual Keyword */ }    
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 82 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(CHAR) /* Contextual Keyword */ } 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 88 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(IntegerLiteral) /* Decimal interger literal */ }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 89 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(IntegerLiteral) /* Hex interger literal */ }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 90 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(IntegerLiteral) /* Octal interger literal */ }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 91 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(IntegerLiteral) /* Binary interger literal */ }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 93 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(FloatingPointLiteral) /* Decimal float literal */ }                                
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 94 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(FloatingPointLiteral) /* Decimal float literal */ }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 95 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(FloatingPointLiteral) /* Decimal float literal */ }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 96 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(FloatingPointLiteral) /* Decimal float literal */ }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 98 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(FloatingPointLiteral) /* Hex float literal */ } 
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 99 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(FloatingPointLiteral) /* Hex float literal */ } 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 101 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(BooleanLiteral) /* Boolean literal */ } 
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 103 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(CharacterLiteral) /* Character literal */ }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 104 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(StringLiteral) /* String literal */ } 
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 106 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(TextBlock) /* TextBlock */ }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 108 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(NullLiteral) /* Null literal */ }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 116 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(DOTDOTDOT)}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(EQ)}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(GQ)}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 119 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(LQ)}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 120 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(NE)}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 121 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(AND)}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 122 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(OR) /* OPERATORS END */}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 123 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(INCRE) /*OPERATORS BEGIN*/}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 124 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(DECRE)}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 125 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(LL)}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 126 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(GGG) /*OPERATORS BEGIN*/}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 127 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(GG) /* OPERATORS END */}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 131 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(ASSIGN)}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 132 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(ASSIGN)}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 133 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(ASSIGN)}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 134 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(ASSIGN)}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 135 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(ASSIGN)}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 138 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(OPEN) /*SEPARRATORS BEGIN*/}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 139 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(CLOSE)}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 140 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(OBRAC)}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 141 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(CBRAC)}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 142 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(SQOPEN)}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 143 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(SQCLOSE)}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 144 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(SEMICOLON)}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 145 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(COMMA)}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 146 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(DOT)}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 147 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(EQUAL) /*OPERATORS BEGIN*/}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 148 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(GT)}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 149 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(LT)}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 150 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(NOT)}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 151 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(NEG)}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 152 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(QUES)}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 153 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(COLON)}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 157 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(PLUS)}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 158 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(MINUS)}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 159 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(MULT)}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 160 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(DIV)}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 161 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(BITAND)}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 162 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(BITOR)}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 163 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(BITCAP)}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 164 "lexer.l"
{ yylval.ST.sym = strdup(yytext); HANDLE(PERCENT)}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 168 "lexer.l"
{  yylval.ST.sym = strdup(yytext); HANDLE(Identifier) }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 176 "lexer.l"
{ printf("Line %d : Error: Illegal character \'%c\' \n", yylineno, yytext[0]);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 178 "lexer.l"
ECHO;
	YY_BREAK
#line 1595 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 348 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 348 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 347);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 178 "lexer.l"

